CREATE TABLE sem1 (
  username VARCHAR(100) NOT NULL,
  subject1 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject2 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject3 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject4 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject5 DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (username));
  
CREATE TABLE sem2 (
  username VARCHAR(100) NOT NULL,
  subject1 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject2 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject3 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject4 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject5 DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (username));
  
  CREATE TABLE sem3 (
  username VARCHAR(100) NOT NULL,
  subject1 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject2 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject3 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject4 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject5 DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (username));
  
  CREATE TABLE sem4 (
  username VARCHAR(100) NOT NULL,
  subject1 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject2 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject3 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject4 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject5 DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (username));
  
  CREATE TABLE sem5 (
  username VARCHAR(100) NOT NULL,
  subject1 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject2 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject3 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject4 DECIMAL(5,2) NOT NULL DEFAULT 0,
  subject5 DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (username));